services:
  db:
    image: postgres:16
    container_name: student-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: apassword123
      POSTGRES_DB: school
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/initdb/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/initdb/02_demo.sql:/docker-entrypoint-initdb.d/02_demo.sql

volumes:
  postgres_data:
